name = "animeforthat"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm install --legacy-peer-deps && npx @cloudflare/next-on-pages"

[[kv_namespaces]]
binding = "QUIZ_COUNTER"
id = "PASTE_YOUR_KV_NAMESPACE_ID_HERE"

[vars]
NEXT_PUBLIC_SITE_URL = "https://animeforthat.com"
NEXT_PUBLIC_CONVERTKIT_FORM_ID = "PASTE_CONVERTKIT_FORM_ID_HERE"
